// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Booking"
          text="Ready to shine? Book your mobile car wash today."
          primaryButton={{
            text: "Call Us: +34 656474532",
            href: "tel:+34656474532",
          }}
          secondaryButton={{
            text: "Email: matteoronsies@gmail.com",
            href: "mailto:matteoronsies@gmail.com",
          }}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
