// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTwoColumn from '@/components/sections/faq/FaqTwoColumn';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTwoColumn
          tag="Info"
          title="Frequently Asked Questions"
          description="Answers to common questions about our car wash services."
          items={[
            {
              question: "Do you come to my home?",
              answer: "Yes, we are a mobile service and will come to your location.",
            },
            {
              question: "What is the surcharge for SUVs?",
              answer: "SUV/vans have a small surcharge of +€10.",
            },
            {
              question: "How do I book a wash?",
              answer: "You can book via WhatsApp, phone (+34 656474532), or email.",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
