// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardCarousel from '@/components/sections/hero/HeroBillboardCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardCarousel
          tag="Lava2 Mobile Car Wash"
          title="We bring the sparkle to your driveway."
          description="Professional exterior, interior, and detailing treatments that make your car shine. Serving you at home."
          primaryButton={{
            text: "Book via WhatsApp",
            href: "https://wa.me/34656474532",
          }}
          secondaryButton={{
            text: "Email us",
            href: "mailto:matteoronsies@gmail.com",
          }}
          items={[
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3HmIunhUsPJFEwuG291xChkZ9Bs/uploaded-1786966380592-kfigd504.png",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3HmIunhUsPJFEwuG291xChkZ9Bs/uploaded-1786966380593-g1to3c97.png",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3HmIunhUsPJFEwuG291xChkZ9Bs/uploaded-1786966380594-3fbl24s2.png?_wi=1",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3HmIunhUsPJFEwuG291xChkZ9Bs/uploaded-1786966380594-qhvohb13.png",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/beautiful-car-washing-service_23-2149212208.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/luggage-seen-from-rear-car-window_23-2150934355.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
