// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "loyalty" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function LoyaltySection(): React.JSX.Element {
  return (
    <div id="loyalty" data-section="loyalty">
        <SectionErrorBoundary name="loyalty">
              <MetricsSimpleCards
          tag="Customer Rewards"
          title="Loyalty Program"
          description="Your loyalty is rewarded. After 10 washes, get your 11th one absolutely free!"
          metrics={[
            {
              value: "10",
              description: "Washes completed",
            },
            {
              value: "1",
              description: "Free wash earned",
            },
            {
              value: "24/7",
              description: "Commitment to quality",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
