// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "pricing" section.

import React from 'react';
import PricingHighlightedCards from '@/components/sections/pricing/PricingHighlightedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PricingSection(): React.JSX.Element {
  return (
    <div id="pricing" data-section="pricing">
        <SectionErrorBoundary name="pricing">
              <PricingHighlightedCards
          tag="Transparency"
          title="Affordable Price List"
          description="Premium mobile car wash services at competitive rates."
          plans={[
            {
              tag: "Essential",
              price: "12 €",
              description: "Basic exterior wash.",
              features: [
                "Hand wash",
                "Tire shine",
                "Glass cleaning",
              ],
              primaryButton: {
                text: "Book Now",
                href: "https://wa.me/34656474532",
              },
            },
            {
              tag: "Popular",
              price: "30 €",
              description: "Standard interior & exterior.",
              features: [
                "Hand wash",
                "Full vacuum",
                "Interior wipe down",
                "Glass",
              ],
              highlight: "Best Value",
              primaryButton: {
                text: "Book Now",
                href: "https://wa.me/34656474532",
              },
            },
            {
              tag: "Elite",
              price: "40 €",
              description: "Complete professional wash.",
              features: [
                "Complete interior",
                "Complete exterior",
                "Detailing",
                "Tire shine",
              ],
              primaryButton: {
                text: "Book Now",
                href: "https://wa.me/34656474532",
              },
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
