/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { useState } from "react";
import { Sparkles, Briefcase, Wind, X, ZoomIn } from 'lucide-react';
import type { LucideIcon } from "lucide-react";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import { resolveIcon } from "@/utils/resolve-icon";

const items = [
  {
    icon: Sparkles,
    title: "Exterior Detailing",
    description: "Hand wash, wax, and premium exterior treatments."
  },
  {
    icon: Briefcase,
    title: "Interior Cleaning",
    description: "Vacuuming, upholstery care, and disinfection."
  },
  {
    icon: Wind,
    title: "Ozone Treatment",
    description: "Eliminate odors and bacteria effectively."
  }
];

type AboutFeaturesSplitProps = {
  tag: string;
  title: string;
  description: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  items: { icon: string | LucideIcon; title: string; description: string }[];
  textAnimation: "slide-up" | "fade-blur" | "fade";
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const ServicesInline = () => {
  const [isOpen, setIsOpen] = useState(false);
  const imageSrc = "https://storage.googleapis.com/webild/users/user_3HmIunhUsPJFEwuG291xChkZ9Bs/uploaded-1786968133840-rs5sgl19.png";

  return (
    <section aria-label="About section" className="py-20">
      <div className="flex flex-col gap-8 md:gap-10 mx-auto w-content-width">
        <div className="flex flex-col items-center gap-2">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Our Expertise"}</p>
          </div>

          <TextAnimation
            text={"Comprehensive Car Care"}
            variant={"slide-up"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"We offer a wide range of services to keep your vehicle in top condition, from basic washes to deep upholstery cleaning."}
            variant={"slide-up"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
            </div>
          )}
        </div>

        <div className="flex flex-col md:flex-row md:items-stretch gap-5">
          <div className="flex flex-col justify-center gap-4 xl:gap-5 2xl:gap-6 p-6 xl:p-7 2xl:p-8 w-full md:w-4/10 2xl:w-35/100 card rounded">
            {items.map((item, index) => {
              const ItemIcon = resolveIcon(item.icon);
              return (
              <div key={item.title}>
                <div className="flex flex-col gap-2">
                  <div className="flex items-center justify-center shrink-0 mb-1 size-10 primary-button rounded">
                    <ItemIcon className="h-2/5 w-2/5 text-primary-cta-text" strokeWidth={1.5} />
                  </div>
                  <h3 className="text-2xl font-semibold">{item.title}</h3>
                  <p className="text-base leading-snug">{item.description}</p>
                </div>
                {index < items.length - 1 && (
                  <div className="mt-4 xl:mt-5 2xl:mt-6 border-b border-accent/40" />
                )}
              </div>
              );
            })}
          </div>

          <div className="p-px w-full md:w-6/10 2xl:w-7/10 h-80 md:h-auto card rounded overflow-hidden group cursor-pointer relative" onClick={() => setIsOpen(true)}>
            <div className="relative size-full">
              <ImageOrVideo imageSrc={imageSrc} className="absolute inset-0 object-cover rounded transition-transform duration-300 group-hover:scale-105" />
              <div className="absolute inset-0 bg-black/30 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center rounded">
                <span className="flex items-center gap-2 text-white bg-black/60 px-4 py-2 rounded-full text-sm font-medium backdrop-blur-sm">
                  <ZoomIn className="w-4 h-4" /> Click to enlarge
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {isOpen && (
        <div 
          className="fixed inset-0 z-50 bg-black/90 backdrop-blur-md flex items-center justify-center p-4 md:p-10 cursor-pointer animate-in fade-in duration-200"
          onClick={() => setIsOpen(false)}
        >
          <button 
            onClick={(e) => { e.stopPropagation(); setIsOpen(false); }}
            className="absolute top-6 right-6 text-white p-2 bg-white/10 hover:bg-white/20 rounded-full transition-colors z-10"
            aria-label="Close"
          >
            <X className="w-6 h-6" />
          </button>
          <div className="relative max-w-5xl max-h-[90vh] w-full h-full flex items-center justify-center" onClick={(e) => e.stopPropagation()}>
            <img 
              src={imageSrc} 
              alt="Services detail full view" 
              className="max-w-full max-h-full object-contain rounded-lg shadow-2xl"
            />
          </div>
        </div>
      )}
    </section>
  );
};

export default function ServicesSection() {
  return (
    <div data-webild-section="services" data-section="services" id="services">
      <ServicesInline />
    </div>
  );
}
