// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import { Briefcase, Sparkles, Wind } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <AboutFeaturesSplit
        tag="Our Expertise"
        title="Comprehensive Car Care"
        description="We offer a wide range of services to keep your vehicle in top condition, from basic washes to deep upholstery cleaning."
        items={[
            {
              icon: Sparkles,
              title: "Exterior Detailing",
              description: "Hand wash, wax, and premium exterior treatments.",
            },
            {
              icon: Briefcase,
              title: "Interior Cleaning",
              description: "Vacuuming, upholstery care, and disinfection.",
            },
            {
              icon: Wind,
              title: "Ozone Treatment",
              description: "Eliminate odors and bacteria effectively.",
            },
          ]}
        imageSrc="https://images.unsplash.com/photo-1607860108855-64acf2078ed9?auto=format&fit=crop&w=1200&q=80"
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}